home:
    path:     /
    defaults: { _controller: AclClassifiedBundle:Home:index }

admin:
    path:     /admin
    defaults: { _controller: AclClassifiedBundle:Security:dumpAdminString }

login:
    path:     /login
    defaults: {_controller: AclClassifiedBundle:Security:login }
login_check:
    path:     /login_check
logout:
    path:     /logout

timetable:
    path:     /timetable
    defaults: {_controller: AclClassifiedBundle:Timetable:view }
timetable_new:
    path:     /timetable/new
    defaults: {_controller: AclClassifiedBundle:Timetable:new }


account_register:
    path:     /register
    defaults: {_controller: AclClassifiedBundle:Account:register }

account_create:
    path:     /register/create
    defaults: {_controller: AclClassifiedBundle:Account:create }

dashboard:
    path:     /dashboard
    defaults: {_controller: AclClassifiedBundle:Dashboard:index }
