parameters:
    acl_classified.handler.login_success_handler.class: Acl\ClassifiedBundle\Handler\LoginSuccessHandler
services:
    login_success_handler:
        class:     %acl_classified.handler.login_success_handler.class%
        arguments: [@router, @security.authorization_checker]

