security:
    encoders:
        Acl\ClassifiedBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        main:
            entity:
                class:     AclClassifiedBundle:User
                property:  email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                username_parameter: _email
            logout:
                path:   /logout
                target:   /
    access_control:
        - { path: ^/dashboard, roles: ROLE_USER }
